#Seeing the World
places = ['tokyo', 'london', 'nara', 'sapporo', 'antarctica']
print(places)
print(sorted(places))
print(places)
print(sorted(places,reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)